#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[workspace]
members = [
  "commons/zenoh-buffers",
  "commons/zenoh-cfg-properties",
  "commons/zenoh-codec",
  "commons/zenoh-collections",
  "commons/zenoh-config",
  "commons/zenoh-core",
  "commons/zenoh-crypto",
  "commons/zenoh-macros",
  "commons/zenoh-protocol",
  "commons/zenoh-shm",
  "commons/zenoh-sync",
  "commons/zenoh-util",
  "examples",
  "io/zenoh-link",
  "io/zenoh-link-commons",
  "io/zenoh-links/zenoh-link-quic/",
  "io/zenoh-links/zenoh-link-tcp/",
  "io/zenoh-links/zenoh-link-tls/",
  "io/zenoh-links/zenoh-link-udp/",
  "io/zenoh-links/zenoh-link-unixsock_stream/",
  "io/zenoh-links/zenoh-link-serial",
  "io/zenoh-links/zenoh-link-ws/",
  "io/zenoh-transport",
  "plugins/example-plugin",
  "plugins/zenoh-backend-traits",
  "plugins/zenoh-plugin-rest",
  "plugins/zenoh-plugin-storage-manager",
  "plugins/zenoh-plugin-trait",
  "zenoh",
  "zenoh-ext",
  "zenohd",
]

[workspace.package]
rust-version = "1.62.1"
version = "0.7.0-rc" # Zenoh version
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = [
    "kydos <angelo@icorsaro.net>",
    "Julien Enoch <julien@enoch.fr>",
    "Olivier Hécart <olivier.hecart@zettascale.tech>",
    "Luca Cominardi <luca.cominardi@zettascale.tech>",
    "Pierre Avital <pierre.avital@zettascale.tech>",
]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]

[workspace.dependencies]
async-global-executor = "2.3.1"
async-std = "=1.12.0"
async-trait = "0.1.59"
base64 = "0.20.0"
clap = "3.2.23"
env_logger = "0.10.0"
event-listener = "2.5.3"
flume = "0.10.14"
form_urlencoded = "1.1.0"
futures = "0.3.25"
git-version = "0.3.5"
hex = "0.4.3"
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
ordered-float = "3.4.0"
petgraph = "0.6.2"
rand = "0.8.5"
regex = "1.7.0"
rustc_version = "0.4.0"
serde = "1.0.149"
serde_json = "1.0.89"
socket2 = "0.4.7"
stop-token = "0.7.0"
uhlc = { git = "https://github.com/atolab/uhlc-rs.git" } # TODO: Using github source until the no_std update gets released on crates.io
uuid = { version = "1.2.2", features = ["v4"] }
vec_map = "0.8.2"

[profile.dev]
debug = true
opt-level = 0

[profile.fast]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false

[profile.release]
debug = false     # If you want debug symbol in release mode, set the env variable: RUSTFLAGS=-g
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
