#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
rust-version.workspace = true
name = "zenoh-util"
version.workspace = true
repository.workspace = true
homepage.workspace = true
authors = [
    "kydos <angelo@icorsaro.net>",
    "Luca Cominardi <luca.cominardi@zettascale.tech>",
    "Pierre Avital <pierre.avital@zettascale.tech>",
]
edition.workspace = true
license.workspace = true
categories.workspace = true
description = "Internal crate for zenoh."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["compat"]
compat = [
    "zenoh-cfg-properties",
    "zenoh-crypto",
    "zenoh-sync",
    "zenoh-collections"
]

[dependencies]
async-std.workspace = true
async-trait.workspace = true
clap.workspace = true
flume.workspace = true
futures.workspace = true
hex.workspace = true
home.workspace = true
humantime.workspace = true
lazy_static.workspace = true
libloading.workspace = true
log.workspace = true
shellexpand.workspace = true
zenoh-cfg-properties = { version = "0.7.0-rc", path = "../zenoh-cfg-properties/", optional = true }
zenoh-collections = { version = "0.7.0-rc", path = "../zenoh-collections/", optional = true }
zenoh-core = { version = "0.7.0-rc", path = "../zenoh-core/" }
zenoh-crypto = { version = "0.7.0-rc", path = "../zenoh-crypto/", optional = true }
zenoh-sync = { version = "0.7.0-rc", path = "../zenoh-sync/", optional = true }

[target.'cfg(windows)'.dependencies]
winapi.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
pnet.workspace = true
pnet_datalink.workspace = true
